inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - 'lib/regexgen/regex.rb'
    - 'lib/regexgen/ast.rb'

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
